-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOisIe/aj6h4m6ZnW
NZMEi1FzArba+A8UAZfNbnxKuIWgCgYIKoZIzj0DAQehRANCAAQIZRLU+lQckiAo
Hr67kuQubaBQFjH8t0pnKlWp0Y1cG6UuuV3yGoqEzKlPmffdslMsad63Un2krAor
DpjbYzEz
-----END PRIVATE KEY-----