# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# FASTLANE_USER=tai.nguyenkim@gmail.com
# FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=lori-gkcv-clpy-ortj

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "TestiOSApp.xcodeproj")
    build_app(scheme: "TestiOSApp")
    upload_to_testflight
  end

  lane :release do
    sync_code_signing
    disable_automatic_code_signing(path: "TestiOSApp.xcodeproj")
    build_app
    enable_automatic_code_signing(path: "TestiOSApp.xcodeproj")
    upload_to_testflight
  end
end
